# Generated by Django 3.2.7 on 2021-09-11 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=10000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('od_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to=settings.AUTH_USER_MODEL)),
                ('zd_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='za_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
