# Generated by Django 3.2.7 on 2021-09-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poruke',
            old_name='zd_user',
            new_name='za_user',
        ),
    ]
