# Generated by Django 3.2.7 on 2021-09-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profili', '0003_rename_slika_profila_account_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
